### ISSUE TITLE
GetLink (std::string videoID) doesn't work

### ISSUE THREAD

**Issue by MorDeCaii** [agabani/YouTube-Download-Library#11]
It seems that this function also doesn't work in demo.exe

**Comment by Bloodwyn** [comment]
Exact same problem. Has something changed with the youtube get_video_info stuff?

**Comment by agabani** [comment]
Sorry, this library is depreciated. Youtube has changed their API's several times since 2014 when this library was written. I'll update the README.md to let future developers know.

**Comment by 0xfaru** [comment]
please let me know if it works @agabani

**Comment by superpowermanyob** [comment]
the problem is fixed???????
